version: '3'

networks:
  gidget:

services:
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    networks:
      - gidget
  php:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    networks:
      - gidget
    volumes:
      - ./backend:/backend
  nginx:
    depends_on:
      - node
      - php
    image: nginx:stable-alpine
    networks:
      - gidget
    ports:
      - 8080:80
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/backend
  db:
    image: postgres:11.5-alpine
    networks:
      - gidget
    volumes:
      - ./db-data:/var/lib/postgresql/data
