version: '3.7'

networks:
  gidget:

services:
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    networks:
      - gidget
  php:
    command: 'php artisan serve -v --host=0.0.0.0'
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    networks:
      - gidget
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  nginx:
    depends_on:
      - node
      - php
    image: nginx:stable-alpine
    networks:
      - gidget
    ports:
      - 8080:80
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/backend
  db:
    image: postgres:11.5-alpine
    networks:
      - gidget
    environment:
      - POSTGRES_USER=gidget
      - POSTGRES_PASSWORD=gidget
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  db-admin:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - gidget
