version: '3'

networks:
  gidget:

services:
  php:
    build:
      context: ./app/php
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: php
    networks:
      - gidget
    volumes:
      - ./backend:/backend

  web:
    depends_on:
      - php
    image: nginx:stable-alpine
    networks:
      - gidget
    ports:
      - 8080:80
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/backend
      - ./frontend:/frontend
