#!/usr/bin/env bash

# Run an artisan command.
# Usage: ./artisan {command}
# Examples:
#   ./artisan migrate
#   ./artisan serve
#   ./artisan list

cd "${0%/*}"
[[ "$1" = 'serve' ]] && ARGS='--host=0.0.0.0'
exec ./php artisan $ARGS $@
