#!/usr/bin/env bash
cd "${0%/*}/../laradock"

export NGINX_HOST_HTTP_PORT=8000

case $1 in
  start|up)
    docker-compose up -d postgres nginx
    ;;

  stop|down)
    exec docker-compose down
    ;;

  phpunit)
    CMD="/var/www/vendor/bin/phpunit ${@:2}"
    ;;

  *)
    docker-compose up -d postgres nginx
    CMD='bash'
    ;;
esac
exec docker-compose exec --user=laradock workspace $CMD
