#!/usr/bin/env bash
cd "${0%/*}/../laradock"

case $1 in
  phpunit)
    CMD="/var/www/vendor/bin/phpunit ${@:2}"
    ;;

  *)
    CMD='bash'
    ;;
esac

exec docker-compose exec --user=laradock workspace $CMD
