#!/usr/bin/env bash
cd "${0%/*}/../laradock"

case $1 in
  start|up)
    exec docker-compose up -d postgres nginx
    ;;

  stop|down)
    exec docker-compose down
    ;;

  phpunit)
    CMD="/var/www/vendor/bin/phpunit ${@:2}"
    ;;

  *)
    CMD='bash'
    ;;
esac

docker-compose exec --user=laradock workspace $CMD || \
  echo "Run \`$0 start\` to start containers."
