#!/usr/bin/env bash

#
# This script must be ran from the project's root directory.
# Usage: ./scripts/setup_dev_backend
#

# Start database before anything to give it as much time as it needs
docker-compose down
docker-compose up -d db

# Copy _env to .env if .env does not exist
[[ ! -f ./backend/.env ]] && cp backend/_env backend/.env && echo 'Copied .env'

# Run composer install and generate keys
php() { docker-compose run --rm php $@;  }
php composer install
php artisan key:generate

# The next commands require the database. We must be sure it's up but there's
# no easy way to actually know if its done being provisioned, so just wait.
echo 'Waiting for 30 seconds to give database time to create itself...'
sleep 30

# Run initial migrations
php artisan migrate

# Create passport keys
php artisan passport:install
