#!/usr/bin/env bash

#
# This script must be ran from the project's root directory.
# Usage: ./scripts/setup_dev_frontend
#

# Ensure node exists
which npm || (echo -e "\nNodeJS and/or NPM do not seem to be installed." && exit 1)

# Run npm install in frontend
cd ./frontend
npm install
