#!/usr/bin/env bash

#
# Usage: ./setup_dev
#

cd "./${0%/*}/.."  # cd to project root

# Clone laradock submodule
if [[ -d './laradock' ]]; then
  [[ ! -d './laradock/.git' ]] && \
    echo 'ERROR: Laradock directory exists but is not a submodule.' && exit 1
else
  git clone 'https://github.com/Laradock/laradock.git' || exit 1
fi

# Create environment files
[[ ! -f './laradock/.env' ]] && \
  ln -sf ./config/laradock_env ./laradock/.env && \
  echo 'Installed laradock .env'

[[ ! -f './backend/.env' ]] && \
  ln -sf ./config/laravel_env ./backend/.env && \
  echo 'Installed laravel .env'

cd ./laradock

# Start database before anything to give it as much time as it needs
docker-compose down
docker-compose up -d postgres nginx

CMD='composer install;'
CMD+='php artisan key:generate;'
CMD+='php artisan migrate;'
CMD+='php artisan passport:install;'
CMD+='php artisan ide-helper:generate;'

# PHP helper
exec docker-compose run --rm --user=laradock workspace sh -c "$CMD"
